### ISSUE TITLE
Failed to activate the Termrk package

### ISSUE THREAD

**Issue by ProgramFan** [romgrk/termrk#54]
**Atom Version**: 1.0.7
**System**: "Fedora release
**Thrown From**: [Termrk](https://github.com/romgrk/termrk) package, v0.1.25
### Stack Trace

Failed to activate the Termrk package

```
At Cannot find module 'season'

Error: Cannot find module 'season'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/zyang/.config/atom/packages/Termrk/lib/termrk.coffee:6:25)
  at Object.<anonymous> (/home/zyang/.config/atom/packages/Termrk/lib/termrk.coffee:3:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:261:14)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:239:14)
  at /usr/share/atom/resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at space-pen-button.<anonymous> (/home/zyang/.config/atom/packages/tool-bar/lib/tool-bar-button-view.coffee:28:25)
  at space-pen-button.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-button.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:01.0 termrk:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "travis-ci-status",
      "pandoc",
      "markmon-preview",
      "japanese-wrap",
      "symbols-view",
      "autocomplete",
      "tool-bar-main",
      "git-projects",
      "remote-edit"
    ],
    "autoHideMenuBar": true
  },
  "Termrk": {
    "fontFamily": "PowerlineSymbols, Dejavu Sans Mono, Source Han Sans CN, monospace",
    "fontSize": "20px"
  }
}
```
### Installed Packages

``` coffee
# User
AtomicChar, v0.3.8
Termrk, v0.1.25
asciidoc-preview, v0.6.0
atom-ctags, v4.1.4
autocomplete-paths, v1.0.2
build, v0.43.0
clipboard-plus, v0.5.1
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.6.3
flex-tool-bar, v0.4.4
formatter, v2.12.3
formatter-clang-format, v0.1.1
formatter-coffeescript, v0.1.1
imdone-atom, v1.1.19
language-asciidoc, v0.11.1
language-cmake, v0.1.4
language-x86asm, v0.5.1
linter, v1.3.4
linter-pep8, v1.0.1
markdown-table-formatter, v2.5.2
minimap, v4.12.3
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.2.1
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
pdf-view, v0.23.0
project-manager, v1.15.11
tool-bar, v0.1.8
tree-view-finder, v0.2.1
vim-mode, v0.58.0
visual-bell, v1.0.0
wordcount, v2.2.2
you-complete-me, v0.6.2

# Dev
No dev packages
```

**Comment by romgrk** [comment]
Fixed by efdaf40c8942d31fbc42c4e7f09c03d55e363ca5.

**Comment by ghost** [comment]
Not sure if issue #56 is related....but seems like its still an issue

**Comment by sbrl** [comment]
I just got this issue.

Stack trace:

```
TypeError: Cannot read property 'getURI' of undefined
  at Object.Utils.getCurrentDir (/home/sbrl/.atom/packages/Termrk/lib/utils.coffee:61:58)
  at TermrkConfig.getStartingDir (/home/sbrl/.atom/packages/Termrk/lib/config.coffee:119:35)
  at TermrkModel.module.exports.TermrkModel.spawnProcess (/home/sbrl/.atom/packages/Termrk/lib/termrk-model.coffee:60:34)
  at new TermrkModel (/home/sbrl/.atom/packages/Termrk/lib/termrk-model.coffee:50:10)
  at TermrkView.module.exports.TermrkView.start (/home/sbrl/.atom/packages/Termrk/lib/termrk-view.coffee:100:22)
  at Object.module.exports.Termrk.createTerminal (/home/sbrl/.atom/packages/Termrk/lib/termrk.coffee:160:20)
  at Object.module.exports.Termrk.activate (/home/sbrl/.atom/packages/Termrk/lib/termrk.coffee:108:29)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:232:19)
  at /opt/atom/resources/app.asar/src/package.js:802:25
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:224:20)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:243:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:20)
```

uname -a: `Linux Snowflake 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by romgrk** [comment]
Hello @sbrl !
Thanks for your feedback, it's always welcome. 
However, I think this should rather be a separate issue, so don't hesitate to create one! 
Also, I need more data in order to debug properly! Please provide steps to reproduce, or at least a minimal context (what where you doing, what are your settings, etc.)

Note: Replaced `getURI` by `getPath`. https://github.com/romgrk/termrk/commit/4f49c948e75d2a9001b4689cee7b00546540f608

**Comment by sbrl** [comment]
@romgrk Ok, I'll file another bug. I haven't recieved this issue again for a while though, so I'll only file one if I get it again.
